project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"

website:
  title: "Elements of Data Analysis and Statistics - Lab Exercises"
  site-url: "https://VOTRE-USERNAME.github.io/VOTRE-REPO/"
  repo-url: "https://github.com/VOTRE-USERNAME/VOTRE-REPO"
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Projects
        contents:
          - qmd/01-pivot-tables-with-libreoffice.qmd
          - qmd/03-discharge-elbe.qmd
          - qmd/04-distributions-leaves.qmd
          - qmd/05-distributions-fruits-tidyverse.qmd
          - qmd/test_stat.qmd
      - section: Presentations
        contents:
          - qmd/06-classical-tests.qmd
      - section: other
        contents:
          - qmd/other.qmd

format:
  html:
    theme: light
    css: thpe.css
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show code"
    code-link: true
    code-overflow: scroll
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - top=20mm
      - left=25mm
      - bottom=25mm

# Configuration WebR
webr:
  packages: ["dplyr", "ggplot2", "readxl", "tidyr", "lubridate", "car", "lmtest"]

execute:
  freeze: auto
  cache: true
  echo: false
  warning: false
  message: false

bibliography: bib.bib
csl: apa.csl